import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="../public/faviconblack.png" />
        {/* You can also use other favicon formats if needed */}
        {/* <link rel="icon" href="/favicon.png" type="image/png" /> */}
        {/* <link rel="icon" href="/favicon.svg" type="image/svg+xml" /> */}
      </head>
      <body className={inter.className}>
        {children}
      </body>
    </html>
  );
}
